### PR TITLE
Compatibility updates for KSP 1.3

### PR DESCRIPTION
**Pull request by HebaruSan**
http://forum.kerbalspaceprogram.com/index.php?/topic/157804-modders-notes-for-13/

- BaseEventData -> BaseEventDetails
- dialogName param for PopupDialog.SpawnPopupDialog

This gets it to compile with KSP 1.3 for me. I have not done user testing though.

### CODE REVIEW

**Comment by PhineasFreak** [comment]
The minor and revision values of the version checker also needs to be updated (nothing will be broken but PP will complain about the mismatched version number): https://github.com/Starwaster/ProceduralParts/blob/master/Source/zzVersionChecker.cs#L68

**Comment by HebaruSan** [comment]
Like that? I assume the version-gen stuff will be handled when you add version tags in git for the release.

**Comment by PhineasFreak** [comment]
No, this is a hardcoded check. It is manually updated every time a new KSP version is released: https://github.com/Swamp-Ig/ProceduralParts/pull/225/files (example from the original PP repository).

**Comment by HebaruSan** [comment]
Yeah, that's what I did in commit e25d54e, I thought. I was just making a side note about some of the other version handling stuff I noticed in the package.

**Comment by PhineasFreak** [comment]
Sorry, i was not very informative in my post. Yes, your PR is perfect. The rest of the versioning stuff are handled, as you said, upon the release of a new package update.

**Comment by HebaruSan** [comment]
Cool! No hurry, by the way. I'm attempting a new mod that integrates with this one, so the first step was getting it up and running in 1.3, and I figured I might as well share the needed changes.

**Comment by HebaruSan** [comment]
I don't know whether you're using that .version file in GameData, but it was also out of date and had the pieces in the wrong order. Previous commit should help.

**Comment by bradb007** [comment]
HebaruSan, thanks for the changes.  is there anyway to get the functional files.  I don't have experience compiling and don't know how to get the dll built.

**Comment by HebaruSan** [comment]
@bradb007 , I recommend waiting for the official update. I'm not going to try to teach you C#, Unity, and KSP programming in a github comment thread.

**Comment by Starwaster** [comment]
I'm going to hold off on this for now. Before I make changes for KSP 1.3, I want to make sure certain other issues get taken care of and then push a last update out for KSP 1.2.2.

Once that's taken care of then we'll get to KSP 1.3

**Comment by Starwaster** [comment]
Merged, finally. Should be able to get the actual update out soon but I think it would be best to wait until the last update makes it to CKAN so that those still on KSP 1.2.2 can find it easily? (not sure how necessary that is; I don't know if CKAN crawls through past updates)

**Comment by HebaruSan** [comment]
Cool! One last note, I just recently noticed that there's an old ModuleManager DLL in the GameData folder. Somehow it wasn't crashing my game, but it's probably safest to update or remove it.

**Comment by Starwaster** [comment]
It's parts with old plugins that crash the game; it happens during part compilation. Module Manager is at 2.8.0 which is what's there now, and the zipped archives all have the appropriate versions of MM. You probably saw it in the repository while it was between updates?

**Comment by HebaruSan** [comment]
Right, I was referring to the state that this pull request left it in. If it's 2.8.0 now, then there's nothing to be concerned about.

**Pull request merged**
